module.exports = {
  SESSION_KEY_UNIQUE_ID: '03475592-a3f8-4054-a188-c793f068d823',

  ERROR_CREATE_SESSION_REQUEST_FAILED: 'ERROR_CREATE_SESSION_REQUEST_FAILED',
  ERROR_CREATE_SESSION_FAILED: 'ERROR_CREATE_SESSION_FAILED',
  ERROR_WX_LOGIN_FAILED: 'ERROR_WX_LOGIN_FAILED',
  ERROR_WX_GET_USER_INFO_FAILED: 'ERROR_WX_GET_USER_INFO_FAILED',
  ERROR_WX_REQUEST_FAILED: 'ERROR_WX_REQUEST_FAILED',
  ERROR_REQUEST_CLIENT_ERROR: 'ERROR_REQUEST_CLIENT_ERROR',
  ERROR_REQUEST_REDIRECT_ERROR: 'ERROR_REQUEST_REDIRECT_ERROR',
  ERROR_REQUEST_SERVER_ERROR: 'ERROR_REQUEST_SERVER_ERROR'
};
